version: '3.0'
services:
  app:
    build: ./src/PhpWebApp
    depends_on:
      - db
    container_name: app
    environment:
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: php -S 0.0.0.0:80
    ports:
      - "80:80"
  db:
    build: ./src/Database
    container_name: hive
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
  ai:
    build: ./src/Ai
    container_name: ai
    command: flask --app app run -h 0.0.0.0 --debug
    ports:
      - "5000:5000"