version: '3.0'

services:
  web:
    build: ./PhpWebApp
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./Database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive